### ISSUE TITLE
Searching only searches for artists

### ISSUE THREAD

**Issue by JeppeTh** [fuzeman/Spotify2.bundle#1]
It would be nice if searching worked like it normally does with 
"top results"
"tracks"
"artists"
"albums"

**Comment by fuzeman** [comment]
**New search results view:**
![](http://i.imgur.com/WFxdCbG.png)

Just have a few more things to finish off before it's released.

**Comment by JeppeTh** [comment]
Thx!

**Comment by JeppeTh** [comment]
Is "top results" not available in api's, or did you just not find it necessary?  I guess top results kind of means most popular, and perhaps sorting in the search categories are sorted by popularity? 

I guess it's not necessary,  since the top result taken from one of the categories.

**Comment by fuzeman** [comment]
Yeah, couldn't see it in the API. Left-most items are basically the top items anyway.
