### ISSUE TITLE
Login no longer works...

### ISSUE THREAD

**Issue by JeppeTh** [fuzeman/Spotify2.bundle#10]
...or at least you get login failure when trying to fetch playlists.

**Comment by fuzeman** [comment]
Will look at this issue now

**Comment by fuzeman** [comment]
Looks like a change to the Spotify authentication process broke it, similar issue over at node-spotify-web https://github.com/TooTallNate/node-spotify-web/issues/81

**Comment by fuzeman** [comment]
Fixed in v0.4.1
