### ISSUE TITLE
Never Connect...

### ISSUE THREAD

**Issue by jquintana-tiqueteo** [fuzeman/Spotify2.bundle#17]
Hi! I have a premium account of spotify and i cant connect in the app. My user is facebook based in other apps the login process is little complicate facebook send me a OTP for sms and connect with that but here not work nothing

**Comment by fuzeman** [comment]
Currently you can't use facebook login directly, you will need to set a device password at http://www.spotify.com/account/set-device-password/ this page should also give you a numeric username to use instead of your email address.

**Comment by fuzeman** [comment]
I'm guessing this is resolved, so will close the issue now. Let me know if this isn't the case.
