### ISSUE TITLE
Playlist view crashes

### ISSUE THREAD

**Issue by heskja** [fuzeman/Spotify2.bundle#18]
Hi,

When trying to view all playlists, I simply get the message "This channel is not responding". I can search for tracks, view starred tracks etc, but not view playlists.

See the attached logs here: 
http://xbmclogs.com/show.php?id=197736

**Comment by fuzeman** [comment]
Thought this bug was fixed v0.4.2, which version of the plugin are you currently using?

Easiest way to determine the current version is by finding the following log entry (in the plugin log file):

```
2014-05-11 04:00:56,322 (4270) :  INFO (logkit:16) - Starting Spotify (version 0.4.3)
```

**Comment by fuzeman** [comment]
I'm guessing this is resolved, so will close the issue now. Let me know if this isn't the case.

**Comment by heskja** [comment]
Hi,

Sorry for the late response. I used Unsupported Appstore to download the
latest version. The logs gives me this:

2014-05-15 17:19:42,221 (1620) :  INFO (logkit:16) - Starting Spotify (version 0.4.3)

Best regards

2014-05-14 5:27 GMT+02:00 Dean Gardiner notifications@github.com:
