### ISSUE TITLE
"Your Music" collection views

### ISSUE THREAD

**Issue by fuzeman** [fuzeman/Spotify2.bundle#20]

**Comment by pablorusso** [comment]
I have added some of this functionality in my fork. As I am using this "project" as a way to learn python, I am not sure what would you think about it, but anyway let me know if you think a PR would help.

**Comment by fuzeman** [comment]
Great to see someone got this implemented, been pretty busy with other projects and fixes to streaming on this plugin.

I'll try have your changes merged into the plugin in the next few days.

**Comment by pablorusso** [comment]
In case you want to include my changes, I have created PR #22
