### ISSUE TITLE
Authentication failure

### ISSUE THREAD

**Issue by fuzeman** [fuzeman/Spotify2.bundle#21]

**Comment by brucys** [comment]
Same issue, I cannot log into Spotify with Plex Channel. Looking forward to a resolve. Cheers

**Comment by AndreSteenbergen** [comment]
Hey guys,

adammw made a brute force attempt to get it working. My python isn't that strong, but I guess you might be able to get it in.
https://gist.github.com/adammw/7f192694c3ed0b13f1f9

**Comment by fuzeman** [comment]
Yeah, will have a new release out very soon which includes that fix.

**Comment by fuzeman** [comment]
There is a fix in v0.4.4 (stable) and v0.5.1 (beta) now
