### ISSUE TITLE
Can't set auth setting from PHT

### ISSUE THREAD

**Issue by ryanrhee** [fuzeman/Spotify2.bundle#28]
Hard to explain, so I have a screen capture instead.
https://www.dropbox.com/s/a8nmynealjmhwsv/spotify2_error.mov

**Comment by fuzeman** [comment]
There was a bug with channel preferences in PHT awhile back, can't see this issue in the latest PlexPass version of PHT (v1.1.3.296) though.

Have you tried setting the channel preferences from Plex/Web? if this doesn't work, send the plugin log files so I can find out what's happening (see the [Support](https://github.com/fuzeman/Spotify2.bundle/wiki/Support) page for details).

**Comment by ryanrhee** [comment]
Thanks for your help. I tried using Plex/Web says the plugin isn't responding. Do you want the log files?

**Comment by ryanrhee** [comment]
You can close, this works.
Unfortunately, I'm still blocked on #43. :(
