### ISSUE TITLE
next track/prev track on Plex htpc

### ISSUE THREAD

**Issue by kaohlive** [fuzeman/Spotify2.bundle#4]
While on the big screen using Plex htpc I can not use a next track option, its missing on the now playing screen. I am sure if my remote would have a button it would work, but a button/controls would be nice.

**Comment by fuzeman** [comment]
This was more a PHT issue, but it looks like PHT v1.1.2.293 (PlexPass?) has these controls now, along with a number of extra features.

**Now Playing**
![](http://i.imgur.com/ZGUj8xz.jpg)

**Now Playing (with queue)**
![](http://i.imgur.com/ZC2LTzL.jpg)

**Home Screen**
![](http://i.imgur.com/Ha1GL9h.png)

**Popup Status**
![](http://i.imgur.com/pZBgmf4.jpg)
