### ISSUE TITLE
Gapless

### ISSUE THREAD

**Issue by EldarAron** [fuzeman/Spotify2.bundle#45]
Is it possible to add gapless playback?
I often listen to concert albums or Armin van Buuren's A state of trance. witch is a radio program. It sounds a bit strange to have the silence between the tracks. So gapless playback would be really nice. Official Spotify app/program supports this.

**Comment by Ph1975** [comment]
bump!

**Comment by fuzeman** [comment]
Gap-less playback of tracks is more of a client issue (PHT, Plex/Web, etc..) , some minor tweaks can be made to the streaming server for specific clients but this would probably only result in a small improvement.
