### ISSUE TITLE
how to set the High-Quality-Streaming  high bit rate 320kbps ?

### ISSUE THREAD

**Issue by fcaeiro** [fuzeman/Spotify2.bundle#47]
its possible to have an option to change to highbitrate like this 

https://support.spotify.com/pt/learn-more/guides/#!/article/If-you-re-a-Premium-user-you-can-try-High-Quality-Streaming

looking at the code to see if i could find a parameter to do so ... but no clue yet

thanks

**Comment by fuzeman** [comment]
duplicate of #44
