### ISSUE TITLE
How to display character other than english?

### ISSUE THREAD

**Issue by chienlim** [fuzeman/Spotify2.bundle#55]

**Comment by chienlim** [comment]
Found the problem in utils.py:

<pre><b>def normalize(text):
    if text is None:
        return None
    if type(text) is Framework.components.localization.LocalString:
        text = str(text)
    if type(text) is unicode:
        text = unicodedata.normalize('NFKD', text)
    return text.encode('ascii', 'ignore')</b></pre>

Not sure why encode the return text to ascii, replace this line:

<pre><b> return text.encode('ascii', 'ignore')</B></pre>

to

<pre><b> return text</b></pre>

fixed the problem.

**Comment by fuzeman** [comment]
When this plugin was originally built plex had issues decoding unicode characters on some operating systems, this is why all the characters are normalized currently. Not sure if plex has fixed unicode support yet..

**Comment by chienlim** [comment]
Thanks
