### ISSUE TITLE
[ERROR] PngFlash2 - service unavailable

### ISSUE THREAD

**Issue by cool3pehr** [fuzeman/Spotify2.bundle#63]
I get the following error: [ERROR] PngFlash2 - service unavailable

I am using my Spotify Canada account and was wondering is this only restricted to US accounts?

Thanks!

**Comment by fuzeman** [comment]
This issue should be fixed now.

**Note:** Certain Plex clients/devices may not work with this plugin or have slow buffering times, can't really do much to fix those issues :disappointed: 

> I am using my Spotify Canada account and was wondering is this only restricted to US accounts?

This plugin should work with all accounts.
